CFG_TEE_TA_LOG_LEVEL ?= 4
CPPFLAGS += -DCFG_TEE_TA_LOG_LEVEL=$(CFG_TEE_TA_LOG_LEVEL)

# The UUID for the Trusted Application
BINARY=0db7bc40-29e5-11e7-93ae-92361f002671

include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
